// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd/server/configpb/config.proto

package configpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	WebuiPort            int32    `protobuf:"varint,3,opt,name=webui_port,json=webuiPort,proto3" json:"webui_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2c30eb88bea0d25, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Config) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Config) GetWebuiPort() int32 {
	if m != nil {
		return m.WebuiPort
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "config.Config")
}

func init() { proto.RegisterFile("cmd/server/configpb/config.proto", fileDescriptor_b2c30eb88bea0d25) }

var fileDescriptor_b2c30eb88bea0d25 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0xce, 0x4d, 0xd1,
	0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x2f, 0x48, 0x82,
	0x32, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8, 0x20, 0x3c, 0xa5, 0x40, 0x2e, 0x36, 0x67,
	0x30, 0x4b, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0x3f, 0x3b, 0x35, 0x4f, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x08, 0xc2, 0x11, 0x12, 0xe2, 0x62, 0x29, 0xc8, 0x2f, 0x2a, 0x91, 0x60, 0x52, 0x60, 0xd4,
	0x60, 0x0d, 0x02, 0xb3, 0x85, 0x64, 0xb9, 0xb8, 0xca, 0x53, 0x93, 0x4a, 0x33, 0xe3, 0xc1, 0x32,
	0xcc, 0x60, 0x19, 0x4e, 0xb0, 0x48, 0x40, 0x7e, 0x51, 0x89, 0x13, 0x57, 0x14, 0x07, 0xcc, 0xce,
	0x24, 0x36, 0xb0, 0x6d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0xd7, 0xff, 0x3d, 0x91,
	0x00, 0x00, 0x00,
}
