// Code generated by protoc-gen-go. DO NOT EDIT.
// source: irremotepb/irremote.proto

package irremotepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action struct {
	RemoteId             string   `protobuf:"bytes,1,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Repeat               int32    `protobuf:"varint,3,opt,name=repeat,proto3" json:"repeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a91b872702a0e6, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetRemoteId() string {
	if m != nil {
		return m.RemoteId
	}
	return ""
}

func (m *Action) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Action) GetRepeat() int32 {
	if m != nil {
		return m.Repeat
	}
	return 0
}

type Request struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Action               *Action  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a91b872702a0e6, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Request) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *Request) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type Code struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a91b872702a0e6, []int{2}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Code) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Remote struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 []*Code  `protobuf:"bytes,2,rep,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Remote) Reset()         { *m = Remote{} }
func (m *Remote) String() string { return proto.CompactTextString(m) }
func (*Remote) ProtoMessage()    {}
func (*Remote) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a91b872702a0e6, []int{3}
}

func (m *Remote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Remote.Unmarshal(m, b)
}
func (m *Remote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Remote.Marshal(b, m, deterministic)
}
func (m *Remote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Remote.Merge(m, src)
}
func (m *Remote) XXX_Size() int {
	return xxx_messageInfo_Remote.Size(m)
}
func (m *Remote) XXX_DiscardUnknown() {
	xxx_messageInfo_Remote.DiscardUnknown(m)
}

var xxx_messageInfo_Remote proto.InternalMessageInfo

func (m *Remote) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Remote) GetCode() []*Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func init() {
	proto.RegisterType((*Action)(nil), "irremote.Action")
	proto.RegisterType((*Request)(nil), "irremote.Request")
	proto.RegisterType((*Code)(nil), "irremote.Code")
	proto.RegisterType((*Remote)(nil), "irremote.Remote")
}

func init() { proto.RegisterFile("irremotepb/irremote.proto", fileDescriptor_f4a91b872702a0e6) }

var fileDescriptor_f4a91b872702a0e6 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4e, 0x03, 0x31,
	0x10, 0x84, 0x75, 0x5c, 0x70, 0x92, 0x0d, 0x42, 0xd1, 0x16, 0xe8, 0x10, 0x4d, 0xe4, 0xca, 0xd5,
	0x21, 0x85, 0x17, 0xe0, 0xa7, 0x4a, 0xeb, 0x06, 0x89, 0x06, 0xf9, 0xec, 0x2d, 0x8c, 0xe4, 0xf3,
	0x61, 0x0c, 0xbc, 0x3e, 0xf2, 0xcf, 0x25, 0x14, 0xe9, 0x66, 0x66, 0xb5, 0xdf, 0x8e, 0x16, 0x6e,
	0x6d, 0x08, 0xe4, 0x7c, 0xa4, 0x69, 0xb8, 0x9f, 0x65, 0x3f, 0x05, 0x1f, 0x3d, 0xae, 0x66, 0xcf,
	0x5f, 0x81, 0x3d, 0xe9, 0x68, 0xfd, 0x88, 0x77, 0xb0, 0x2e, 0xd9, 0xbb, 0x35, 0x5d, 0xb3, 0x6b,
	0xc4, 0x5a, 0xae, 0x4a, 0x70, 0x30, 0xd8, 0xc1, 0x52, 0x7b, 0xe7, 0xd4, 0x68, 0xba, 0x8b, 0x3c,
	0x9a, 0x2d, 0xde, 0x00, 0x0b, 0x34, 0x91, 0x8a, 0x5d, 0xbb, 0x6b, 0xc4, 0xa5, 0xac, 0x8e, 0x0f,
	0xb0, 0x94, 0xf4, 0xf9, 0x4d, 0x5f, 0x31, 0x91, 0x0d, 0xfd, 0x58, 0xfd, 0x9f, 0x5c, 0x82, 0x83,
	0xc1, 0x2d, 0xb4, 0x1f, 0xbf, 0xb1, 0x52, 0x93, 0x44, 0x01, 0x4c, 0xe5, 0x4a, 0x99, 0xb8, 0xd9,
	0x6f, 0xfb, 0x63, 0xfb, 0x52, 0x55, 0xd6, 0x39, 0xef, 0x61, 0xf1, 0xe2, 0x0d, 0x21, 0xc2, 0x62,
	0x54, 0x8e, 0x2a, 0x3b, 0xeb, 0x94, 0x69, 0x6f, 0xa8, 0x82, 0xb3, 0xe6, 0x8f, 0xc0, 0x64, 0x06,
	0x9d, 0xdd, 0xe0, 0xc7, 0x8d, 0x56, 0x6c, 0xf6, 0xd7, 0xa7, 0xab, 0xe9, 0x46, 0x21, 0x3c, 0x5f,
	0xbd, 0xc1, 0xe9, 0xab, 0x03, 0xcb, 0xdf, 0x7c, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xe6,
	0x0b, 0x2f, 0x6a, 0x01, 0x00, 0x00,
}
