// Code generated by protoc-gen-go. DO NOT EDIT.
// source: irremote.proto

package irremotepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action struct {
	RemoteId             string   `protobuf:"bytes,1,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Repeat               int32    `protobuf:"varint,3,opt,name=repeat,proto3" json:"repeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b3ee5d8bce4364, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetRemoteId() string {
	if m != nil {
		return m.RemoteId
	}
	return ""
}

func (m *Action) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Action) GetRepeat() int32 {
	if m != nil {
		return m.Repeat
	}
	return 0
}

type Request struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Action               *Action  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b3ee5d8bce4364, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Request) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *Request) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func init() {
	proto.RegisterType((*Action)(nil), "irremote.Action")
	proto.RegisterType((*Request)(nil), "irremote.Request")
}

func init() { proto.RegisterFile("irremote.proto", fileDescriptor_f4b3ee5d8bce4364) }

var fileDescriptor_f4b3ee5d8bce4364 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2c, 0x2a, 0x4a,
	0xcd, 0xcd, 0x2f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xc2,
	0xb9, 0xd8, 0x1c, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x84, 0xa4, 0xb9, 0x38, 0x21, 0x62, 0xf1, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x1c, 0x10, 0x01, 0xcf, 0x14, 0x21, 0x09, 0x2e,
	0xf6, 0xe4, 0xfc, 0xdc, 0xdc, 0xc4, 0xbc, 0x14, 0x09, 0x26, 0xb0, 0x14, 0x8c, 0x2b, 0x24, 0xc6,
	0xc5, 0x56, 0x94, 0x5a, 0x90, 0x9a, 0x58, 0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5,
	0x29, 0x25, 0x71, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x80, 0x4c, 0x4e, 0x49, 0x2d,
	0xcb, 0x4c, 0x46, 0x36, 0x19, 0x22, 0xe0, 0x99, 0x22, 0x24, 0xc0, 0xc5, 0x9c, 0x55, 0x5e, 0x02,
	0x35, 0x15, 0xc4, 0x14, 0xd2, 0xe0, 0x62, 0x4b, 0x04, 0x3b, 0x09, 0x6c, 0x22, 0xb7, 0x91, 0x80,
	0x1e, 0xdc, 0xf5, 0x10, 0xa7, 0x06, 0x41, 0xe5, 0x9d, 0x78, 0xa2, 0xb8, 0x60, 0x52, 0x05, 0x49,
	0x49, 0x6c, 0x60, 0xbf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xeb, 0x96, 0x33, 0xed,
	0x00, 0x00, 0x00,
}
